name: CI

on:
  push:
    branches: [ main, develop, '**/*' ]
  pull_request:

jobs:
  test:
    name: Node ${{ matrix.node }} • ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Run coverage
        run: npm run coverage
        env:
          CI: true

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-node-${{ matrix.node }}
          path: coverage/
          if-no-files-found: ignore

      - name: Build package
        run: npm run build

      - name: Verify built files exist
        run: |
          test -f dist/index.mjs
          test -f dist/index.cjs
          test -f dist/index.d.ts
